// Generated by CoffeeScript 1.8.0
(function() {
  app.controller("MigrateController", function($scope, $controller, $http) {
    $controller("BaseController", {
      $scope: $scope
    });
    $scope.loading = true;
    $scope.updateStatus();
    $scope.migrate = function(backupId) {
      var data, request;
      $scope.status.restore_running = true;
      $scope.status.step_description = "Setting up migration.";
      data = {
        action: "bits_restore_from_backup",
        id: backupId
      };
      request = $http({
        url: ajaxurl,
        method: "post",
        params: data
      });
      request.success(function() {
        return $scope.updateStatus();
      });
      return $scope.step_description = "Starting migration.  You can cancel at any step.";
    };
    $scope.getSites = function() {
      var request;
      request = $http({
        url: ajaxurl,
        method: "GET",
        params: {
          action: "bits_backup_get_sites"
        }
      });
      return request.success(function(data, status) {
        var site;
        $scope.sites = (function() {
          var _i, _len, _ref, _results;
          _ref = data['sites'];
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            site = _ref[_i];
            if (site.name !== null) {
              _results.push(site);
            }
          }
          return _results;
        })();
        $scope.currentSiteId = data['current_site_id'];
        $scope.list();
        return $scope.loading = false;
      });
    };
    $scope.selectSite = function(siteId) {
      return $scope.list(siteId);
    };
    return $scope.getSites();
  });

}).call(this);
