// Generated by CoffeeScript 1.8.0
(function() {
  app.controller("RestoreController", function($scope, $controller, $http) {
    $controller("BaseController", {
      $scope: $scope
    });
    $scope.loading = true;
    $scope.updateStatus();
    $scope.restoreFromBackup = function() {
      var data, request;
      $scope.status.restore_running = true;
      $scope.status.step_description = "Preparing.";
      data = {
        action: "bits_restore_from_backup",
        id: $scope.selectedBackup.id
      };
      request = $http({
        url: ajaxurl,
        method: "post",
        params: data
      });
      request.success(function() {
        return $scope.updateStatus();
      });
      return $scope.step_description = "Starting restore.  You can cancel at any step.";
    };
    return $scope.list();
  });

}).call(this);
