// Generated by CoffeeScript 1.8.0
(function() {
  app.controller("SettingsController", function($scope, $http, $controller) {
    $controller("BaseController", {
      $scope: $scope
    });
    $scope.updateStatus();
    return $scope.saveSettings = function() {
      var data, request;
      data = {
        action: "bits_backup_save_settings",
        selected_site: $scope.selected_site
      };
      request = $http({
        url: ajaxurl,
        method: "POST",
        params: data
      });
      return request.success((function(_this) {
        return function(data, status, headers, config) {
          return setTimeout(updateStatus, 1);
        };
      })(this));
    };
  });

}).call(this);
