// Generated by CoffeeScript 1.8.0
(function() {
  app.controller("SettingsController", function($scope, $http) {
    $scope.getSites = function() {
      var request;
      request = $http({
        url: ajaxurl,
        method: "GET",
        params: {
          action: "bits_backup_get_sites"
        }
      });
      return request.success(function(data, status) {
        var site;
        $scope.sites = (function() {
          var _i, _len, _ref, _results;
          _ref = data['sites'];
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            site = _ref[_i];
            if (site.name !== null) {
              _results.push(site);
            }
          }
          return _results;
        })();
        return $scope.selected_site = data['current_site_id'];
      });
    };
    $scope.saveSettings = function() {
      var data, request;
      data = {
        action: "bits_backup_save_settings",
        selected_site: $scope.selected_site
      };
      request = $http({
        url: ajaxurl,
        method: "POST",
        params: data
      });
      return request.success((function(_this) {
        return function(data, status, headers, config) {
          return setTimeout(updateStatus, 1);
        };
      })(this));
    };
    return $scope.getSites();
  });

}).call(this);
